"""Constants used throughout the Ketchup backend."""

# Venue Categories
VENUE_CATEGORIES = [
    "restaurant",
    "cafe",
    "bar",
    "dessert",
    "night_club",
]

# Feedback Types
FEEDBACK_TYPE_LOVED = "LOVED"
FEEDBACK_TYPE_LIKED = "LIKED"
FEEDBACK_TYPE_DISLIKED = "DISLIKED"

FEEDBACK_TYPES = [
    FEEDBACK_TYPE_LOVED,
    FEEDBACK_TYPE_LIKED,
    FEEDBACK_TYPE_DISLIKED,
]

# User Availability
TIMEZONE_UTC = "UTC"
MIN_AVAILABLE_MINUTES = 30  # Minimum availability window in minutes
MAX_AVAILABLE_MINUTES = 480  # Maximum availability window in minutes (8 hours)

# Venue Metadata
MIN_VENUE_RATING = 0.0
MAX_VENUE_RATING = 5.0

MIN_PRICE_LEVEL = 1
MAX_PRICE_LEVEL = 4

# Geographic
EARTH_RADIUS_KM = 6371
MIN_LATITUDE = -90.0
MAX_LATITUDE = 90.0
MIN_LONGITUDE = -180.0
MAX_LONGITUDE = 180.0

# Distance thresholds
MAX_DISTANCE_KM = 50  # Maximum distance to search for venues
DEFAULT_SEARCH_RADIUS_METERS = 5000

# API Rate Limiting
API_TIMEOUT_SECONDS = 30
API_MAX_RETRIES = 3
API_BACKOFF_FACTOR = 0.5  # Exponential backoff multiplier

# Caching
CACHE_TTL_SECONDS = 86400  # 24 hours
CACHE_VENUE_PREFIX = "venue:"
CACHE_CALENDAR_PREFIX = "calendar:"
CACHE_ROUTE_PREFIX = "route:"

# Event Generation
MAX_EVENT_OPTIONS = 10
MIN_EVENT_OPTIONS = 2
PREFERENCE_WEIGHT_CATEGORIES = 0.3
PREFERENCE_WEIGHT_PRICE = 0.2
PREFERENCE_WEIGHT_DISTANCE = 0.5

# Data Validation
MAX_GROUP_SIZE = 50
MIN_GROUP_SIZE = 2
MAX_EVENT_TITLE_LENGTH = 256
MAX_EVENT_DESCRIPTION_LENGTH = 2000

# Firestore Collections
COLLECTION_USERS = "users"
COLLECTION_GROUPS = "groups"
COLLECTION_VENUES = "venues"
COLLECTION_CALENDAR_DATA = "calendar_data"
COLLECTION_VOTES = "votes"
COLLECTION_EVENT_OPTIONS = "event_options"
COLLECTION_FINALIZED_EVENTS = "finalized_events"
COLLECTION_POST_EVENT_RATINGS = "post_event_ratings"
COLLECTION_FEEDBACK_HISTORY = "feedback_history"

# BigQuery Tables
BIGQUERY_TABLE_USERS = "users"
BIGQUERY_TABLE_VENUES = "venues"
BIGQUERY_TABLE_EVENTS = "events"
BIGQUERY_TABLE_FEEDBACK = "feedback"
BIGQUERY_TABLE_METRICS = "pipeline_metrics"

# Logging
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_LEVEL_DEBUG = "DEBUG"
LOG_LEVEL_INFO = "INFO"
LOG_LEVEL_WARNING = "WARNING"
LOG_LEVEL_ERROR = "ERROR"
LOG_LEVEL_CRITICAL = "CRITICAL"

# Feature Flags
FEATURE_CACHING_ENABLED = True
FEATURE_CIRCUIT_BREAKER_ENABLED = False
FEATURE_DATA_VALIDATION_ENABLED = True
FEATURE_BIGQUERY_SYNC_ENABLED = True

# Version
VERSION = "0.1.0"
