steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  entrypoint: 'bash'
  secretEnv: ['HF_TOKEN']
  args:
    - -c
    - |
      docker buildx build \
        --tag=${_IMAGE} \
        --secret id=HF_TOKEN \
        .

availableSecrets:
  secretManager:
  - versionName: 'projects/${PROJECT_ID}/secrets/HF_TOKEN/versions/latest'
    env: 'HF_TOKEN'

images: ["${_IMAGE}"]

substitutions:
  _IMAGE: '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_NAME}:latest'
  _REPO: 'qwen3-vllm-repo'
  _NAME: 'qwen3-4b-2507-vllm-tools'

options:
  dynamicSubstitutions: true
  machineType: "E2_HIGHCPU_32"